project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('animeval.urls')),
]+ static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

animeval/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.contrib.auth.base_user import BaseUserManager

# Create your models here.

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.
    Username and password are required. Other fields are optional.
    """
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        #abstract = True # ここを削除しないといけないことを忘れない！！！！！！！！！！

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

class ProfileModel(models.Model):

    GENDER_CHOICES = (
        (1,'男性'),
        (2,'女性'),
        (3,'その他'),
    )

    username = models.ForeignKey(User, on_delete = models.CASCADE,related_name = 'user')
    nickname = models.CharField(max_length = 10,verbose_name = 'ニックネーム')
    gender = models.IntegerField(choices = GENDER_CHOICES, blank = True)
    favarite_anime = models.CharField(max_length = 100)
    

    def __str__(self):
        return self.nickname

class AnimeModel(models.Model):
    anime_title = models.CharField(max_length = 100)
    anime_genre = models.CharField(max_length = 15, default= '0/0/0/0/0/0/0/0')

class ReviewModel(models.Model):

    GENRE_CHOICES = (
        (1,'SF'),
        (2,'ファンタジー'),
        (3,'コメディ'),
        (4,'バトル'),
        (5,'恋愛'),
        (6,'スポーツ'),
        (7,'青春'),
        (8,'戦争'),
    )

    username = models.ForeignKey(User, on_delete = models.CASCADE)
    nickname = models.ForeignKey(ProfileModel, on_delete = models.CASCADE)
    anime_title = models.ForeignKey(AnimeModel, on_delete = models.CASCADE)
    anime_genre = models.IntegerField(choices = GENRE_CHOICES, blank = True)
    review_title = models.CharField(max_length =50)
    review_content = models.TextField()
    evaluation_value = models.CharField(max_length = 9)
    evaluation_value_ave = models.DecimalField(max_digits=2, decimal_places=1)
    post_date = models.DateTimeField(auto_now_add = True)

class Counter(models.Model):
    username = models.ForeignKey(User,on_delete=models.CASCADE)
    genre_counter = models.CharField(max_length = 15, null = True)

class AccessReview(models.Model):
    access_name = models.ForeignKey(User, on_delete = models.CASCADE)
    review = models.ForeignKey(ReviewModel, on_delete = models.CASCADE)

    def __str__(self):
        return 'アクセス名:{} / レビュータイトル:{}'.format(self.access_name.username, self.review.review_title)

class Comment(models.Model):
    comment = models.CharField(max_length = 255)
    review = models.ForeignKey(ReviewModel, on_delete = models.CASCADE)
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)

class ReplyComment(models.Model):
    reply = models.CharField(max_length = 255)
    comment = models.ForeignKey(Comment, on_delete = models.CASCADE)
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)

templates/base.html
{% load static%}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/all.css' %}">

    <title>AnimEval</title>
</head>
<body>
  
    <!-- ナビバー -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'homepage' %}">AnimEval</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% if user.is_authenticated %}
            <a class = 'nav-item nav-link text-dark' href = "{% url 'home' %}">Home</a>
            <a class = 'nav-item nav-link text-dark' href = "#">search</a>
            <a class="nav-item nav-link text-dark" href="{% url 'profile' profile.id %}">mypage</a>
            <a class="nav-item nav-link text-dark" href="{% url 'create_review' %}">投稿</a>
        <div class="d-flex justify-content-center">
          <form class="form-inline my-2" method="GET" action="#">
            <input type="text" class="form-control" name="q" value="{{request.GET.q}}">
            <button type="submit" value="search" class="btn btn-primary">検索</button>
          </form>
        </div>
          <a class="nav-item nav-link text-dark" href="{% url 'profile' profile.id %}"></a>
      </div>
          {% if query %}
          <p class="text-center font-weight-bold h4">{{object_list.count}}件</p>
          {% endif%}

          {% else %}          
          <a class="nav-item nav-link text-dark" href="#">
            ログインはこちらから
          </a>
          <a class="nav-item nav-link text-dark" href="#">
            会員登録はこちらから
          </a>
          {% endif %}
        </ul>
      </div>
    </nav>
    <!-- メインコンテント -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

    <!--フッター-->
    <footer class="footer">
      <div class="container">
        <p class="text-muted">Place sticky footer content here.</p>
      </div>
    </footer>
  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

templates/base2.html
{% load static%}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/all.css' %}">

    <title>AnimEval</title>
</head>
<body>
    <!-- メインコンテント -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

templates/create_comment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id = 'wrapper'>
    <div id = 'comment-form'>
        <div id = 'title'>
            <h4>コメント</h4>
        </div>
        <form action="" method = 'POST'>{% csrf_token %}
            <div id = 'comment'>
                <textarea name="comment" cols="50" rows="5"></textarea>
            </div>
            <div id = 'button'>
                <input type="submit" value = 'コメントする'>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/create_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
</head>
<body>
    <div id = 'wrapper'>
    <form action="" method = 'POST'>{% csrf_token %}
            <section id = 'title'>
                <h1>Create Profile</h1>
            </section>
            <section id = 'item'>
                <div>
                    <p>ユーザー名</p>
                    <input type="text" placeholder = 'ユーザー名' name = 'nickname'>
                </div>
                <div>
                    <p>性別</p>
                    <select name="gender" id="gender">
                        <option value='1'>男性</option>
                        <option value='2'>女性</option>
                        <option value='3'>その他</option>
                    </select>
                </div>
                <div>
                    <p>お気に入りのアニメ</p>
                    <input type="text" placeholder = '複数ある場合は/で区切ってください' name = 'favarite_anime'>
                </div>
            </section>
            <section id = 'button'>
                <input type="submit" value = '登録'>
            </section>
        </form>
    </div>
</body>
</html>

templates/create_reply.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id = 'wrapper'>
    <div id = 'comment-form'>
        <div id = 'title'>
            <h4>コメント</h4>
        </div>
        <form action="" method = 'POST'>{% csrf_token %}
            <div id = 'reply'>
                <textarea name="reply" cols="50" rows="5"></textarea>
            </div>
            <div id = 'button'>
                <input type="submit" value = 'コメントする'>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/create_review.html
{% extends 'base.html' %}
{% load static %} 
{%block content%}
    <link rel="stylesheet" href="{% static '/css/post.css' %}">
    <div id = 'wrapper'>
        <div id = 'review'>
            <section>
                <form action="" method = 'POST'>{% csrf_token %}
                    <input type="text" name = 'anime_title'>
                    <input type="submit" name = 'search' value = '探す'>
                </form>
            </section>
    
            <section id = 'title'>
                <h4>{{context}}</h4>
                <h4>レビューを書いてみよう</h4>
            </section> 
            <section id = 'item'>
                <form action="" method = 'POST'>{% csrf_token %}
                    <div id = 'anime-title'>
                        <p>アニメタイトル</p>
                        <input type="text" placeholder = 'アニメタイトル' name = 'anime_title' value = {{anime_title}}>
                    </div>
                    <div id = 'anime_genre'>
                        <p>ジャンル</p>
                        <p>
                            SF<input type="radio" value = '1' name = 'anime_genre'>
                            ファンタジー<input type="radio" value = '2' name = 'anime_genre'>
                            コメディ<input type="radio" value = '3' name = 'anime_genre'>
                            バトル<input type="radio" value = '4' name = 'anime_genre'>
                            恋愛<input type="radio" value = '5' name = 'anime_genre'>
                            スポーツ<input type="radio" value = '6' name = 'anime_genre'>
                            青春<input type="radio" value = '7' name = 'anime_genre'>
                            戦争<input type="radio" value = '8' name = 'anime_genre'>
                        </p>
                    </div>
                    <div id = 'spoiler-question'>
                        <p>ネタバレを含みますか？</p>
                        <p>
                            No<input type="radio" value = '0' name = 'spoiler' checked = 'checked'>
                            Yes<input type="radio" value = '1' name = 'spoiler'>
                        </p>
                    </div>
                    <div id = 'review-content'>
                        <p>レビュー(1行目はタイトルを記入してください)</p>
                        <textarea name="review_content" id="" cols="50" rows="10"></textarea>
                    </div>
                    <div id = 'evaluation-title'>
                        <p>各項目の評価</p>
                    </div>
                    <div id='evaluation'>
                        <div>
                        <p>ストーリー</p>
                            <select name="val1">
                                <option value=1>1</option>
                                <option value=2>2</option>
                                <option value=3>3</option>
                                <option value=4>4</option>
                                <option value=5>5</option>
                            </select>
                        </div>
                        <div>
                        <p>作画</p>
                            <select name="val2">
                                <option value=1>1</option>
                                <option value=2>2</option>
                                <option value=3>3</option>
                                <option value=4>4</option>
                                <option value=5>5</option>
                            </select>
                        </div>
                        <div>
                        <p>音楽</p>
                            <select name="val3">
                                <option value=1>1</option>
                                <option value=2>2</option>
                                <option value=3>3</option>
                                <option value=4>4</option>
                                <option value=5>5</option>
                            </select>
                        </div>
                        <div>
                        <p>キャラクター</p>
                            <select name="val4">
                                <option value=1>1</option>
                                <option value=2>2</option>
                                <option value=3>3</option>
                                <option value=4>4</option>
                                <option value=5>5</option>
                            </select>
                        </div>
                        <div>
                        <p>声優</p>
                            <select name="val5">
                                <option value=1>1</option>
                                <option value=2>2</option>
                                <option value=3>3</option>
                                <option value=4>4</option>
                                <option value=5>5</option>
                            </select>
                        </div>
                    </div>
                    <div id = 'button'>
                        <input type="submit" value = '登録' name = 'post'>
                    </div>
                </form>
            </section>
        </div>
    </div>
{%endblock content%}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static '/css/all.css' %}">
<link rel="stylesheet" href="{% static '/css/home.css' %}">
<div id = 'wrapper'>
    {% if high_similarity_anime%}
    <section id = 'trend'>
        <div id = 'trend-title'>
            <h4>あなたへのおすすめアニメ</h4>
            <p>Anime : {{high_similarity_anime.anime_title}}</p>
            <p>Genre : {{top_anime_genre}}</p>
        </div>
        <div id = 'trend-title-detail'>
            <ul id = 'trend-title-detail1'>
                <li>
                    <h6>総合順位</h6>
                    <p>{{rank}}位</p>
                </li>
                <li>
                    <h6>平均評価</h6>
                    <p>{{value_ave}}/5.0</p>
                </li>
                <li>
                    <h6>投稿数</h6>
                    <p>{{review_count}} 件</p>
                </li>
            </ul>
        </div>
        <div id = 'trend-graph'>
            <img src="{% url 'trend_image' high_similarity_anime.pk %}" alt="" width = '400' height = '300'>
        </div>
    </section>
    {% endif %}
    {% for review in review_list %}
    <section id = 'review-list'>
        <div id = 'title'>
            <a href="{% url 'review_detail' review.pk %}">
            <div id = 'review-title'>
                <h4>{{review.evaluation_value_ave}}</h4>
                <h4>{{review.review_title}}</h4>
                
            </div>
            </a>
            <div id = 'anime-title'>
                <h6>Anime : {{review.anime_title.anime_title}}</h6>
                <h6>Genre : {{review.anime_genre}}</h6>
            </div>
        </div>
        <div id = 'review-content'>
            <p id = 'content'>{{review.review_content | linebreaksbr}}</p>
            <p id = 'detail-btn'>続きを見る</p>
        </div>
        <div id = 'icon'>
            <p>{{review.nickname.nickname}}</p>
            <p>{{review.post_date}}</p>
            <p>Comment</p>
            <p>いいね</p>
        </div>
    </section>
    {% endfor %}
</div>
<script src = "{% static '/javascript/home.js' %}"></script>
{% endblock content %}

templates/homepage.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/homepage.css' %}">
    <title>Document</title>
</head>
<body>
    <div id = 'wrapper'>
        <section id = 'title'>
            <h1></h1>
        </section>
        <div id = 'enter'>
            <div id = 'enter-context'>
                Press the Enter Key
            </div>
        </div>
        <div id = 'login'>
            <a href="{% url 'signup' %}"><h2>Sign up</h2></a>
            <h2>or</h2>
            <a href="{% url 'login' %}"><h2>Login</h2></a>
        </div>
    </div>
<script src = "{% static '/javascript/homepage.js' %}"></script>
</body>
</html>

templates/login.html
{% extends 'base2.html' %}
{% block content %}
<form action="" method = 'POST'>
    <div class = "col-md-6 offset-md-3">
        <div class = 'card'>
            <div class = 'card-body'>
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.error }}
                    <hr>
                {% endfor %}
                <button type = 'submit' class = 'btn btn-success btn-lg btn-block'>ログイン</button>
                <input type="hidden" name = 'text' value = "{{ next }}">
                {% csrf_token %}
            </div>
        </div>
    </div>
</form>
{% endblock content %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static '/css/home.css' %}">
<link rel="stylesheet" href="{% static '/css/profile.css' %}">

<div id = 'profile'>
    <section id = 'section1'>

        <div id = 'top'>
            <h4>{{profile.nickname}}</h4>
            <img src="#" alt="profile image">
        </div>

        <div id = 'data'>
            <ul id = 'count'>
                <li>
                    <p>{{profile.get_gender_display}}</p>
                    <label for = 'name'>gender</label>
                </li>
                <li>
                    <p>{{profile.favarite_anime}}</p>
                    <label for = 'name'>アニメ</label>
                </li>
                <li>
                    <p>{{review_num}}</p>
                    <label for = 'name'>投稿数</label>
                </li>
            </ul>
            <div id = 'update'>
                <h6>プロフィールを編集</h6>
            </div>
        </div>

    </section>

    <section id = 'section2'>

        <div id = 'list'>
            <div id = 'title'>
                <h6 id = 'title_post'><a href="#">投稿一覧</a></h6>
                <form class="form-inline my-2" method="GET" action="#" id = 'search_box'>
                    <input type = 'search' name = 'search' placeholder = 'キーワードを入力'>
                    <input type="submit" name = 'submit' value = '検索'>
                </form>
            </div>
            <div id = 'review'>
                {% for review in review_list %}
                    <div id = 'review-list'>
                        <div id = 'title1'>
                            <div id = 'review-title'>
                                <h4>{{review.evaluation_value_ave}}</h4>
                                <h4>{{review.review_title}}</h4>
                            </div>
                            <div id = 'anime-title'>
                                <h6>Anime : {{review.anime_title}}</h6>
                            </div>
                        </div>
                            <div id = 'review-content'>
                                <p>{{review.review_content}}</p>
                            </div>
                        <div id = 'icon'>
                            <p>{{review.nickname.nickname}}</p>
                            <p>{{review.post_date}}</p>
                            <p>Comment</p>
                            <p>いいね</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div id = 'context'>
                <h2>{{ context }}</h2>
            </div>
        </div>

    </section>
</div>
{% endblock content %}

templates/review_detail.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <link rel="stylesheet" href="{% static '/css/all.css' %}">
    <link rel="stylesheet" href="{% static '/css/detail.css' %}">

<div id = 'wrapper'>
    <section id = 'section1'>
        <div id = 'review-hedder'>
            <div id = 'review-title'>
                <h4>{{review.review_title}}</h4>
            </div>
            <div id = 'anime-title'>
                <p>Anime : {{review.anime_title.anime_title}}</p>
                <p>Genre : {{review.get_anime_genre_display}}</p>
            </div>
        </div>
        <div id = 'review-content'>
            <p>{{review.review_content}}</p>
        </div>
    </section>
    <section id = 'section2'>
        <div id = 'evaluation-detail'>
            <p>総合評価 : {{review.evaluation_value_ave}}</p>
        </div>
        <div id = 'evaluation-graph'>
            <img src= {% url 'image' review.pk %} width = '600' height = '400'>
        </div>
        <div id = 'comment-list'>
            {% for comment in comment_list %}
                <div id = 'comment-header'>
                    <p>{{comment.user.username}}</p> 
                    <p id = 'comment-date'>{{comment.created_at}}</p>
                </div>
                <div id = 'comment-content'>
                    <p id = 'content'>{{comment.comment}}</p>
                    <a href=""><p>続きを読む</p></a>
                </div>
                <div id = 'reply'>
                    <a href="{% url 'create_reply' comment.pk %}"><p>返信</p></a>
                </div>
                <div>
                    <a href="" id = 'reply-display'>返信を表示する</a>
                    <div id = 'reply-list' style = 'display:none'>
                        {% for reply in reply_list %}
                            {% if reply.comment == comment %}
                            <div id = 'reply-header'>
                                <p>{{reply.user.username}}</p>
                                <p id = 'reply-date'>{{reply.created_at}}</p>
                            </div>
                            <div id = 'reply-content'>
                                <p id = 'content'>{{reply.reply}}</p>
                                <a href=""><p>続きを読む</p></a>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <a href="{% url 'create_comment' review.pk %}">コメントを書く</a>
        </div>
    </section>
    <section id = 'section3'>
        <div id = 'random-review-header'>
            <h4>{{review.username.username}}さんのその他の投稿</h4>
        </div>
        <div id = 'random-review-list'>
            {% for review in review_list%}
                <div id = 'random-review'>
                    <div id = 'random-review-title'>
                        <h6>{{review.evaluation_value_ave}} {{review.review_title}}</h6>
                        <p>Anime : {{review.anime_title.anime_title}}</p>
                    </div>
                    <div id = 'random-review-content'>
                        <p id = 'content'>{{review.review_content}}</p>
                        <a href="{% url 'review_detail' review.pk %}"><p>続きを見る</p></a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
</div>
<script src = "{% static '/javascript/detail.js' %}"></script>

{% endblock content %}

templates/signup.html
{% extends 'base2.html' %}


{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}